---
- name: Ensure Docker service is running
  systemd:
    name: docker
    state: started
    enabled: yes

- name: Ensure Buildx is available
  command: docker buildx version
  register: buildx_check
  changed_when: false

- name: Create or select Buildx builder and bootstrap
  shell: |
    set -euo pipefail
    if ! docker buildx inspect {{ docker_builder_name }} >/dev/null 2>&1; then
      docker buildx create --name {{ docker_builder_name }} --driver docker-container --use
    else
      docker buildx use {{ docker_builder_name }}
    fi
    docker buildx inspect --bootstrap
  args:
    executable: /bin/bash
  changed_when: false

- name: Enable binfmt/QEMU for cross-arch builds
  shell: |
    set -euo pipefail
    docker run --privileged --rm tonistiigi/binfmt --install all
  args:
    executable: /bin/bash
  register: binfmt_out
  changed_when: "'installing' in binfmt_out.stdout or 'updating' in binfmt_out.stdout"